"""empty message

Revision ID: 8a554cb5111d
Revises: c98f1fe660b0
Create Date: 2026-01-09 20:37:45.816228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a554cb5111d'
down_revision = 'c98f1fe660b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_clinical_history', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_column('initial_clinical_history')


    # ### end Alembic commands ###
