"""empty message

Revision ID: 8df63698e7c4
Revises: 6bb9935aa906
Create Date: 2026-01-17 03:25:45.351587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8df63698e7c4'
down_revision = '6bb9935aa906'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['location_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

